spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false
    open-in-view: false

app:
  jwt:
    secret: bXlzdXBlcnNlY3JldGtleWZvcmp3dGF1dGhlbnRpY2F0aW9u
    expiration-ms: 86400000
